# Generated by Django 4.2.1 on 2023-06-02 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('cart', '0003_alter_cart_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prod_id',
            field=models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
