# Generated by Django 4.2.1 on 2023-06-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prod_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
