# Generated by Django 4.2.1 on 2023-06-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('retail_price', models.FloatField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
