# Generated by Django 4.2.1 on 2023-06-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Test', max_length=1000),
            preserve_default=False,
        ),
    ]
