# Generated by Django 2.2.13 on 2023-05-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('retail_price', models.FloatField()),
                ('num_in_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('img', models.URLField()),
            ],
        ),
    ]
