# Generated by Django 4.2.1 on 2023-06-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
        ('camera', '0003_remove_camera_img_remove_camera_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product'),
        ),
    ]
