# Generated by Django 4.2.1 on 2023-06-10 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_manufacturer_alter_product_num_in_stock'),
        ('accessory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='img',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='num_in_stock',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product'),
        ),
    ]
