# Generated by Django 4.2.1 on 2023-06-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_rename_user_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('valid_date', models.DateField()),
                ('cvv', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'db_table': 'payment_card',
            },
        ),
    ]
